### ISSUE TITLE
Duplicate references appear when using GitHub "#" syntax in commit message

### ISSUE THREAD

**Issue by Mark-LaCroix** [rayluo/github-pages-overwriter#1]
Using this Action results in a duplicate of the latest commit on the main branch. This itself is fine, but when a commit message references a GitHub issue using the "#" syntax, two identical messages appear in the issue log.

![image](https://user-images.githubusercontent.com/1129348/151653341-eba52081-35b1-4ea7-a1b9-e2a2da4627ee.png)

Worse, when the next commit comes, and the previous duplicate commit is removed, the reference to it in the issue log remains but becomes a dead link.

For my use case, this is ultimately worth the tremendous utility of this Action, but it kinda breaks GitHub's issue workflow integration, so I wonder if it's fixable.

**Comment by rayluo** [comment]
Hi Robot - hmm, I mean, Mark - thanks for your interest in Github Page Overwriter (GPO)!

Yeah, I noticed that inconvenience of the (seemingly) duplicated commit when I used GPO in my own projects (like [this one](https://github.com/rayluo/easter)), too. I did not previously bother look deep into it, but since you brought this up now, I gave it another look. After investigation, it seems it is an unfortunate side effect of [using non-default `source-directory`](https://github.com/rayluo/easter/blob/main/.github/workflows/publish-to-github-pages.yml#L24). ([Your project does that](https://github.com/NobleRobot/NobleEngine/blob/main/.github/workflows/PublishDocsToGitHubPages.yml#L24), too.) I'll need more time to see whether there would be a fix for it.

Meanwhile, may I suggest the workaround as "refrain from mentioning a github issue in your commit message"? It may not sound like the solution you are seeking for, but, in my own git/github experience, it is usually difficult to get things right in one single commit (unless, well, your screenshot above was about a typo). Normally I would push my commit(s) to a new branch and start a PR for it - regardless of whether I anticipate any discussion in that PR - and then later I can reference or [close the corresponding issue from that PR](https://github.blog/2013-05-14-closing-issues-via-pull-requests/). In this workflow, GPO's duplicated commits won't harm.
